### ISSUE TITLE
Compiling macOS 32 bit causes several ambiguous errors for MemoryBlock

### ISSUE THREAD

**Issue by tadmn** [FigBug/Gin#1]
1. pull latest juce develop tip
2. add gin as module to juce project (using projucer)
3. attempt to compile for i386

**Comment by tadmn** [comment]
Sorry, I should add, the errors aren't ambiguous, but that there is a mac version of MemoryBlock that is clashing with the juce::MemoryBlock, so the identifier is ambiguous ;)

**Comment by FigBug** [comment]
I can't reproduce the error with the Gin demo project. 

Usually these conflicts come from including the macOS system headers after the juce headers, if you reorder your includes does that fix it?
