### ISSUE TITLE
pass by copy??

### ISSUE THREAD

**Issue by matkatmusic** [FigBug/Gin#10]
https://github.com/FigBug/Gin/blob/e3eb07e6a783bbcb2efd942f01b935d11cf8373f/modules/gin/utilities/valuetreeutilities.h#L33

Shouldn't value trees be passed by copy? They're reference-counted, and you have a reference member in this class.

**Comment by FigBug** [comment]
If you pass copy, and the source ValueTree gets redirected, then you stop getting notifications. Therefore I prefer to pass a reference.
