### ISSUE TITLE
ValueTree::Listener now has default implementations for the virtual functions

### ISSUE THREAD

**Issue by matkatmusic** [FigBug/Gin#11]
https://github.com/FigBug/Gin/blob/e3eb07e6a783bbcb2efd942f01b935d11cf8373f/modules/gin/utilities/valuetreeutilities.h#L21

see: https://github.com/WeAreROLI/JUCE/blob/8ec56d15896d687711be348aaace08311ecabcc8/modules/juce_data_structures/values/juce_ValueTree.cpp#L1097

**Comment by FigBug** [comment]
For about 8 months, how did I not notice.
