### ISSUE TITLE
In LevelTracker, only the first channel of the audio buffer is referenced.

### ISSUE THREAD

**Issue by COx2** [FigBug/Gin#15]
Hello Roland,

I found a code that is probably a mistake.
As the title says, only the first channel of the audio buffer is referenced in LevelTracker component.

https://github.com/FigBug/Gin/blob/e6db7bd1e322bb6d6767fa60971b846c0f18b66e/modules/gin_dsp/dsp/gin_leveltracker.cpp#L19

This code is causing, if the plugin can receive stereo signals, the level meter do not respond when the signal is input to the R channel only.
e.g. Compressor and Limiter in the slPlugins repository.
If I change this code as follows,  such behavior will be collected.

`trackBuffer (buffer.getReadPointer (i), buffer.getNumSamples()); `

**Comment by FigBug** [comment]
Yup, looks like you are correct. Either submit a pull request or I'll get to it next time I get a moment.

**Comment by COx2** [comment]
Thank you for your response in https://github.com/FigBug/Gin/commit/44ffdd9be95ab90f7fe1d44ec23466d83a534402
