### ISSUE TITLE
Spline produces NaN if any point has an Y value of zero

### ISSUE THREAD

**Issue by wardnijman** [FigBug/Gin#2]

**Comment by FigBug** [comment]
Not seeing this, can you provide values to reproduce?

**Comment by wardnijman** [comment]
Sure, here is an example:
{1, 0},
{247.306 , 111.54},
{362.056  y:98.4783},
{484.306  y:82.2084},
{750  y:132},
{599.806  y:61.2164},
{750.,  y:132},

**Comment by wardnijman** [comment]
Oops.. After posting I immediately realised there is a duplicate value in there. Seems I am adding zero's in the wrong place, multiple times. Thanks for the work anyways :-)
