### ISSUE TITLE
Knob's text value won't update.

### ISSUE THREAD

**Issue by KottV** [FigBug/Gin#28]
Hi, I think it's a Gin issue. Every knob text label doesn't update on changing:

![изображение](https://user-images.githubusercontent.com/4686351/174195746-734c2598-77fa-4707-834e-9713f1c6b9fd.png)

Standalone and all plugins format. It's on linux (openSUSE TW, X11)

**Comment by FigBug** [comment]
Knobs aren't working at all, they do in debug but not release. Some sort of optimizer issue.

**Comment by FigBug** [comment]
`RealtimeAsyncUpdater` is buggy. Switched back to juce one, will fix realtime later and switch back.
