### ISSUE TITLE
How to use gin::PerlinNoise correctly? 

### ISSUE THREAD

**Issue by matkatmusic** [FigBug/Gin#34]
Hey Roland. 

Thanks for fixing that I assert I posted.

I'm using your Perlin Noise class from Gin.  It's saving us a lot of time, so thanks for making it.

I'm feeding it a 2D array of x/y coordinates ranging from 0 to 1, with the class declared as `gin::PerlinNoise<float>`. 

I'm expecting to see something like this:
![expected noise](https://user-images.githubusercontent.com/2929847/210008494-b6b548a2-8c55-4cc4-945e-4993f1f6a8a3.png)

I'm getting this instead when I use an input range of [0, 1]
<img width="309" alt="Screen Shot 2022-12-29 at 12 43 44 PM" src="https://user-images.githubusercontent.com/2929847/210009420-65585024-1167-4920-85a1-b747dba9e4ca.png">

If I use a higher range, some weird tiling happens:
<img width="303" alt="Screen Shot 2022-12-29 at 12 40 17 PM" src="https://user-images.githubusercontent.com/2929847/210009471-e191e63a-ade9-4aa9-9c8c-fb5a032e9f4d.png">

Is this due to how many octaves you're calculating?

**Comment by FigBug** [comment]
Well that's embarrassing. Both perlin noise constructors were broken. Now it looks like this:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1270305/210014758-2144ab8a-19ba-4af2-8d59-ae27a8c7d0bf.png">
