### ISSUE TITLE
Parameters names and count not used properly for LV2

### ISSUE THREAD

**Issue by Simon-L** [FigBug/Gin#36]
I've encountered this problem while working on PAPU, which supports LV2.

When building the Synth example in LV2 format on Linux, it seems that parameter name and parameter count is not detected properly. There's probably something missing for the lv2 helper program provided by Juce to map everything properly, although manually inspecting the generated `dsp.ttl` file shows the the parameters were indeed found, with the right names and number. 

Below is a screen capture of Carla showing the VST3 version (left) vs the LV2 version (right), showing the missing parameters.
![synthvssynth](https://github.com/FigBug/Gin/assets/2551484/9258b0d9-6791-44b7-b408-4cda96108ade)

**Comment by Simon-L** [comment]
> I've updated to latest juce, does this fix it?
> 
> https://github.com/FigBug/PAPU/actions/runs/5257687948

Yes! Thanks, just grabbed the zip and tried the LV2 in [Ildaeil](https://github.com/DISTRHO/Ildaeil/) and all the parameters show up. I'll have a try at compiling myself later. I noticed the build script uses an APIKEY to connect to what I assume is your own website, but this key apparenty is optional and I could grab some builds. Any version would do though, right?

**Comment by FigBug** [comment]
Yes, API key is optional. Without it, it won't trigger a build of the projucer, but will still download a build if it already exists. It is also used for uploading binaries. 

I should really switch to CMake at some point in the future.
