### ISSUE TITLE
Deprecation warnings in FileSystemWatcher (macOS 13.0)

### ISSUE THREAD

**Issue by rcohen12000** [FigBug/Gin#37]
`FSEventStreamScheduleWithRunLoop` and `FSEventStreamUnscheduleFromRunLoop` are deprecated.  First deprecated in macOS 13.0 - use `FSEventStreamSetDispatchQueue` instead.

**Comment by stfufane** [comment]
Hi, I encountered it and made a local fix that works, how should it be incorporated? Will the replacement of the deprecated methods be compatible with older versions? I can submit my fix attempt in a PR if you want to review it.

**Comment by FigBug** [comment]
Fixed by @stfufane
