### ISSUE TITLE
layout doesn't work on macos when app sandbox is enabled

### ISSUE THREAD

**Issue by modosc** [FigBug/Gin#41]
[this code](https://github.com/FigBug/Gin/blob/master/examples/Synth/Source/Editor.cpp#L24-L30) won't work on macos if app sandbox is enabled. specifically only a single element is rendered:

<img width="1604" alt="image" src="https://github.com/FigBug/Gin/assets/2231664/1a54a7aa-5877-4449-893a-8f5b8de35298">

i ended up getting it to work with this horribleness:
```cpp
void Editor::resized() {
#if JUCE_DEBUG
#if JUCE_MAC
  if (juce::SystemStats::isAppSandboxEnabled()) {
    DBG("disabling layout reloading because AppSandbox is enabled");
    layout.setLayout("layout.json");
  } else {
    auto f = juce::File(__FILE__).getChildFile("../../Resources/layout.json");
    layout.setLayout("layout.json", f);
  }
#else
  auto f = juce::File(__FILE__).getChildFile("../../Resources/layout.json");
  layout.setLayout("layout.json", f);
#endif
#else
  layout.setLayout("layout.json");
#endif
}
```

i'm not suggesting you do this in the demos but maybe a comment about `AppSandbox` compatibility would help the next person who hits this?

**Comment by FigBug** [comment]
Fixed in 42147be1dcb40a6c0b5b6fa719d1ac933ea3b36f
