### ISSUE TITLE
applyBrightnessContrast changes alpha values?

### ISSUE THREAD

**Issue by reFX-Mike** [FigBug/Gin#5]
Changing the brightness affects completely invisible pixels whose alpha values are 0. When used on an image like that, and lowering the brightness, the invisible pixels become visibly darker.

It seems almost as if the alpha values are darkened too.

Note: this function interprets the input value for contrast correctly, so positive values increase contrast, negative values decrease it.

**Comment by FigBug** [comment]
Fixed

**Comment by FigBug** [comment]
Not sure what is happening here, I'm definitely not touching the alpha value.
