### ISSUE TITLE
Fix for filenamelength on Windows

### ISSUE THREAD

**Issue by Normalised** [FigBug/Gin#9]
https://github.com/FigBug/Gin/blob/de3861bdaab42dbc474b88713daf9e91b93dcaaa/modules/gin/utilities/filesystemwatcher.cpp#L208

The fni->FileNameLength field is the size of the file name in bytes, not the number of wchars in the String.

The fix is this :

`e.file = folder.getChildFile(String(fni->FileName, fni->FileNameLength / sizeof(wchar_t)));`

Most of the time you don't see the bug because for single event buffers the byte after the fni record is already null, but when you have multiple events, there is not always a null byte after the end of the string so it was creating invalid filenames.

**Comment by FigBug** [comment]
Thanks. Fixed.
